version: '2'
services:
    blog-app:
        image: blog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=blog-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    blog-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: blog-cassandra
    blog-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=blog-cassandra
    blog-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: blog-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
